// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/plugin.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PluginResponse_SignalType int32

const (
	PluginResponse_METRIC PluginResponse_SignalType = 0
	PluginResponse_TRACE  PluginResponse_SignalType = 1
	PluginResponse_LOG    PluginResponse_SignalType = 2
)

var PluginResponse_SignalType_name = map[int32]string{
	0: "METRIC",
	1: "TRACE",
	2: "LOG",
}

var PluginResponse_SignalType_value = map[string]int32{
	"METRIC": 0,
	"TRACE":  1,
	"LOG":    2,
}

func (x PluginResponse_SignalType) String() string {
	return proto.EnumName(PluginResponse_SignalType_name, int32(x))
}

func (PluginResponse_SignalType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4368bc2f41172306, []int{0, 0}
}

type PluginResponse struct {
	Type                 PluginResponse_SignalType `protobuf:"varint,1,opt,name=type,proto3,enum=opentelemetry.proto.collector.plugin.v1.PluginResponse_SignalType" json:"type,omitempty"`
	Data                 []byte                    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *PluginResponse) Reset()         { *m = PluginResponse{} }
func (m *PluginResponse) String() string { return proto.CompactTextString(m) }
func (*PluginResponse) ProtoMessage()    {}
func (*PluginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4368bc2f41172306, []int{0}
}

func (m *PluginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PluginResponse.Unmarshal(m, b)
}
func (m *PluginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PluginResponse.Marshal(b, m, deterministic)
}
func (m *PluginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PluginResponse.Merge(m, src)
}
func (m *PluginResponse) XXX_Size() int {
	return xxx_messageInfo_PluginResponse.Size(m)
}
func (m *PluginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PluginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PluginResponse proto.InternalMessageInfo

func (m *PluginResponse) GetType() PluginResponse_SignalType {
	if m != nil {
		return m.Type
	}
	return PluginResponse_METRIC
}

func (m *PluginResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type PluginRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PluginRequest) Reset()         { *m = PluginRequest{} }
func (m *PluginRequest) String() string { return proto.CompactTextString(m) }
func (*PluginRequest) ProtoMessage()    {}
func (*PluginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4368bc2f41172306, []int{1}
}

func (m *PluginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PluginRequest.Unmarshal(m, b)
}
func (m *PluginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PluginRequest.Marshal(b, m, deterministic)
}
func (m *PluginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PluginRequest.Merge(m, src)
}
func (m *PluginRequest) XXX_Size() int {
	return xxx_messageInfo_PluginRequest.Size(m)
}
func (m *PluginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PluginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PluginRequest proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("opentelemetry.proto.collector.plugin.v1.PluginResponse_SignalType", PluginResponse_SignalType_name, PluginResponse_SignalType_value)
	proto.RegisterType((*PluginResponse)(nil), "opentelemetry.proto.collector.plugin.v1.PluginResponse")
	proto.RegisterType((*PluginRequest)(nil), "opentelemetry.proto.collector.plugin.v1.PluginRequest")
}

func init() {
	proto.RegisterFile("proto/plugin.proto", fileDescriptor_4368bc2f41172306)
}

var fileDescriptor_4368bc2f41172306 = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0xc8, 0x29, 0x4d, 0xcf, 0xcc, 0xd3, 0x03, 0x73, 0x84, 0xd4, 0xf3, 0x0b, 0x52,
	0xf3, 0x4a, 0x52, 0x73, 0x52, 0x73, 0x53, 0x4b, 0x8a, 0x2a, 0x21, 0x82, 0x7a, 0xc9, 0xf9, 0x39,
	0x39, 0xa9, 0xc9, 0x25, 0xf9, 0x45, 0x7a, 0x50, 0xb5, 0x65, 0x86, 0x4a, 0xab, 0x18, 0xb9, 0xf8,
	0x02, 0xc0, 0xbc, 0xa0, 0xd4, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0xa1, 0x30, 0x2e, 0x96, 0x92,
	0xca, 0x82, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x3e, 0x23, 0x27, 0x3d, 0x22, 0x8d, 0xd2, 0x43,
	0x35, 0x46, 0x2f, 0x38, 0x33, 0x3d, 0x2f, 0x31, 0x27, 0xa4, 0xb2, 0x20, 0x35, 0x08, 0x6c, 0x9e,
	0x90, 0x10, 0x17, 0x4b, 0x4a, 0x62, 0x49, 0xa2, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x4f, 0x10, 0x98,
	0xad, 0xa4, 0xc3, 0xc5, 0x85, 0x50, 0x27, 0xc4, 0xc5, 0xc5, 0xe6, 0xeb, 0x1a, 0x12, 0xe4, 0xe9,
	0x2c, 0xc0, 0x20, 0xc4, 0xc9, 0xc5, 0x1a, 0x12, 0xe4, 0xe8, 0xec, 0x2a, 0xc0, 0x28, 0xc4, 0xce,
	0xc5, 0xec, 0xe3, 0xef, 0x2e, 0xc0, 0xa4, 0xc4, 0xcf, 0xc5, 0x0b, 0xb3, 0xa4, 0xb0, 0x34, 0xb5,
	0xb8, 0xc4, 0xa8, 0x9b, 0x11, 0x26, 0x12, 0x9c, 0x5a, 0x54, 0x96, 0x99, 0x9c, 0x2a, 0x54, 0xc5,
	0xc5, 0x5c, 0x54, 0x9a, 0x27, 0x64, 0x46, 0xb2, 0xab, 0xc1, 0x06, 0x4a, 0x99, 0x93, 0xe9, 0x5b,
	0x25, 0x06, 0x03, 0x46, 0x27, 0xe7, 0x28, 0xc7, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4,
	0xfc, 0x5c, 0x7d, 0x90, 0x41, 0xba, 0x70, 0x93, 0xf4, 0xe1, 0x66, 0xe8, 0x17, 0xa5, 0x26, 0xa7,
	0x66, 0x96, 0xa5, 0x16, 0x41, 0x63, 0x0c, 0xc1, 0x05, 0xd9, 0x95, 0xc4, 0x06, 0xa6, 0x8c, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x01, 0xd5, 0x3a, 0xd6, 0x01, 0x00, 0x00,
}
